AddEventHandler('onClientMapStart', function()
	Wait(9000)
	SendNUIMessage({ action = 'ui', config = Config.ui })
	SendNUIMessage({ action = 'setFont', url = Config.font.url, name = Config.font.name })
end)