--executed = 0
--received = 0
--
--local function Loop()
--    SetTimeout(2, function ()
----        MySQL.Sync.fetchAll('WRONG SQL QUERY', {})
--
--        MySQL.Sync.fetchScalar('SELECT @parameters', {
--            ['@parameters'] =  'string'
--        })
--
--        executed = executed + 1
--
--        MySQL.Async.fetchAll('SELECT "hello2" as world', {}, function(result)
--            received = received + 1
--        end)
--
--        if executed % 100 == 0 then
--            print(received .. "/"  .. executed)
--        end
--
--        Loop()
--    end)
--end
--
--AddEventHandler('onMySQLReady', function ()
--    Loop()
--end)

