rules: "<div style='text-align: center;'><span style='color: red;font-size: 20px;'
>TassieRP Job Information Guide</span></div><div style='text-align: center;'>
<br>Hello Welcome to the Job Information Guide!
<br>
<br>In This guide you will find things like: The Jobs you can do, How to do them, Where to get a job Etc, 
<br>
<br><span style='color: red;'>1.1,<span style='color: green;'>|How to get A Job|
<br>
<br><span style='color: red;'>1.2,<span style='color: green;'> Normal Jobs <span style='color: white;'>
<br>Normal Jobs are Jobs everyone can do! there are a ton of normal jobs that can be done in TassieRP
<br>Some of the normal jobs include |Trucking|Landscaping|Mining|LumberJack|Taxi| Go to --- To see more information
<br>To start doing a job you must head over to the job centre and get obtain one from the circle there 
<br>You can find the Job centre on the map as the blue blip and on the side under Job Centre
<br>Once you have a job you will recieve an in-game hourly salary dependant on the job All jobs have different pay-grades 
<br>
<br>
<br><span style='color: red;'>1.3,<span style='color: green;'> WhiteListed Jobs<span style='color: white;'> 
<br>To Start it's important to mention that some jobs are whitelisted and you must apply for them
<br>The Current Whitelisted Jobs are as followed |Police|EMS|Barista|Mechanic| we will go over these later in greater detail 
<br>These Jobs MUST be applied for and cannot be done with a submitted application 
<br>To Apply for a WhiteListed Job Please Head Over to the TassieRP Discord and go to the WhiteListed-Jobs Section
<br>
<br>
<br><span style='color: red;'>1.4,<span style='color: green;'>|How to Do The Jobs|<span style='color: white;'>
<br>
<br><span style='color: red;'>1.5 <span style='color: green;'>|Land-Scaping|<span style='color: white;'>
<br>To Start Head over the the Job centre and select the job Land-Scaping
<br>Now that you've got the job land-scaping if you hit TAB you will see that above your name it will show your job grade as Land-Scaper
<br>In your Inventory you will notice 3 new items in your inventory |LandscapingGPS| |LandscapingTool| |LandscapingFinish|
<br>To start landScaping please drag all 3 on to your hot-bar or drag LandscapingGPS to the (Use) function provided if dragged to hotbar please hit the number corrisponding if slot 1 press 1 etc 
<br>You will then notice a notification appear saying you've now started landscaping Head-over to your map by pressing ESC 
<br>And you will find a Yellow Blip this is the Landscaping Location Please head to there 
<br>Once at the yellow blip on the map Drag |LandScapingTool| to the hotbar Or Drag the item to the (Use) function provided 
<br>If in the right spot a progress bar will appear and you will start doing the land-scaping job
<br>Once completed you will be paid and experience will be added towards your total level 
<br>The higher the level the higher you will end up getting paid
<br>Once you are finished doing land-scaping and if you have a job active please use the |LandscapingFinish| By using the Hotbar and or (Use) Function provided!
<br>And that's all there is to it! Now you now how to do the land-scaping job! Go out there and make yourself some money!
<br>
<br>
<br>
<br><span style='color: red;'>1.6<span style='color: green;'> |Trucking Job|<span style='color: white;'>
<br>To Start Trucking Head over the the Job centre and select the job Trucking
<br>Now that you've got the job Trucker if you hit TAB you will see that above your name it will show your job grade as Trucker
<br>In your Inventory you will notice 3 new items in your inventory |TruckerGPS| |TruckingDeliver| |TruckingFinish|
<br>To start Trucker please drag TruckerGPS on to your hot-bar or drag TruckerGPS to the (Use) function provided 
<br>if dragged to hotbar please hit the number corrisponding if slot 1 press 1 etc 
<br>You will then notice a notification appear saying you've now started Trucking Head-over to your map by pressing ESC 
<br>Now you will be able to find  a Yellow Blip this is the Trucking Location Please head to there 
<br>Once at the yellow blip on the map Drag |TruckingDeliver| to the hotbar Or Drag the item to the (Use) function provided 
<br>If in the right spot a progress bar will appear and you will start doing the trucker job
<br>Once completed you will be paid and experience will be added towards your total level 
<br>The higher the level the higher you will end up getting paid
<br>Once you are finished doing trucking and if you have a job active please use the |TruckingFinish| By using the Hotbar and or (Use) Function provided!
<br>And that's all there is to it! Now you now how to do the Trucking job! Go out there and make yourself some money!
<br>
<br>
<br><span style='color: red;'>1.7<span style='color: green;'>|Taxi Job|<span style='color: yellow;'>
<br>Current as of 26/04/2021</div> ",